name: Build Shellcheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout Shellcheck
      uses: actions/checkout@v2
      with:
        repository: 'koalaman/shellcheck'
    - name: Setup Haskell
      uses: actions/setup-haskell@master
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Build Shellcheck
      run: |
        cabal v1-install
