name: Build Shellcheck

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Shellcheck
      uses: actions/checkout@v2
      with:
        repository: 'koalaman/shellcheck'
    - name: Setup Haskell
      uses: actions/setup-haskell@master
    - name: Update cabal repo
      run: |
        cabal v1-update
    - name: Build Shellcheck
      run: |
        cabal v1-install
    - name: Find Shellcheck
      run: |
        Get-Command cabal; Get-ChildItem $LOCALAPPDATA; Get-ChildItem $APPDATA
