name: Build Shellcheck

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Shellcheck
      uses: actions/checkout@v2
      with:
        repository: 'koalaman/shellcheck'
    - name: Setup Haskell
      uses: actions/setup-haskell@master
    - name: Update cabal repo
      run: |
        cabal v1-update
    - name: Build Shellcheck
      run: |
        cabal v1-install --bindir=bin
    - name: Run Shellcheck
      run: |
        .\bin\shellcheck.exe --help
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: master
        release_name: master
        body: |
          Some stuff that happens
        draft: true
    - name: Publish release asset
      uses: actions/upload-a-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/shellcheck.exe
        name: shellcheck.exe
        asset_content_type: application/vnd.microsoft.portable-executable
